### ISSUE TITLE
image naming dilemma

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spikeinterface-dockerfiles#4]
I really like the approach of making minimal docker images that contain only the installed sorter, and not the wrapper part. Then spikeforest + spikesorters can both share those base images. However, I now realize we are going to have a confusing naming problem. I have been building images for spikeforest based on the images in these repos, and of course I am also calling them by the name of the sorter like:

spikeinterface/spyking-circus:1.0.7 ------> magland/spyking-circus:1.0.7

the latter of these contains the extra packages needed to work with labbox-ephys and spikeforest

And I assume that spikesorters will need to also create a new container buiding upon the base image. What will that be called?

So while I really like the idea of sharing these minimal base images, I am concerned about the confusing use of the same name. Not sure what to do about it.

Ideas? @jsoules @samuelgarcia @bendichter @alejoe91

**Comment by jsoules** [comment]
call the shared image `base-spyking-circus:1.0.7`? Or `minimal-`?

**Comment by magland** [comment]
@jsoules 
I think that's a good idea, but perhaps `spyking-circus-base:1.0.7`

**Comment by alejoe91** [comment]
I like `sortername-base` :)

**Comment by magland** [comment]
Okay, i'll make that change.

**Comment by magland** [comment]
Created this PR: https://github.com/SpikeInterface/spikeinterface-dockerfiles/pull/6

And I also updated the build.sh/push.sh files in the other PR's

**Comment by magland** [comment]
Also pushed new images to dockerhub, and deleted old dockerhub repos
