### ISSUE TITLE
cannot use compiled KS docker images on dockerhub

### ISSUE THREAD

**Issue by a-zmz** [SpikeInterface/spikeinterface-dockerfiles#55]
hi,

I have tried to use compiled KS2 docker images in SI, but none of the images worked for some reason...
So I installed Docker on my pc (Fedora 36), pulled from https://hub.docker.com/r/spikeinterface/kilosort2-compiled-base and `kilosort3-compiled-base`, then tried to extend the base image to the final image by following the instructions here https://github.com/SpikeInterface/spikeinterface-dockerfiles/tree/main/kilosort_no_license/kilosort2-compiled#3-extending-base-image-and-creating-final-image, I got permission error.

I cannot directly use the base image either, when I do
`sorting_KS2 = ss.run_sorter('kilosort2', recording_saved, 
                            output_folder=base_folder / 'results_KS2',
                            verbose=True, docker_image='spikeinterface/kilosort2-compiled-base:latest', 
                            **sorter_params)`, I got `DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))`.

Could anyone please help? Using a docker image to run ks without matlab licence  is such a nice feature, I am sure people would love to have this working! Thanks!

**Comment by alejoe91** [comment]
Hi @a-zmz 

Sorry this repo is meant just to maintain the images, and I'm seeing this only now. Is this solved? Have you tried with recent versions of SpikeInterface?

**Comment by a-zmz** [comment]
hi i have not yet tried the latest spikeinterface, will try and let you know, thanks!

**Comment by alejoe91** [comment]
@a-zmz should be fixed with recent SI releases as we changed the way we probe for a GPU device. Closing
