### ISSUE TITLE
Use AWS tests for all sorters, not only GPU ones

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeinterface-dockerfiles#62]
@bendichter tests are currently failing because the CI machine runs out of space. Would it be ok to make tests of all containers (not only GPU ones) a chron job running monthly or on manual dispatch?

**Comment by bendichter** [comment]
is there a way to create tests that require less space?

**Comment by alejoe91** [comment]
All tests moved to main SI repo
