### ISSUE TITLE
FileNotFoundError: /spikeinterface_cache/tmpqdx5w1ct/1RCXQKQP/binary.json'

### ISSUE THREAD

**Issue by nimayk** [SpikeInterface/spikeinterface-dockerfiles#65]
Hi I am trying to use spikeinterface with its various containerized spike sorters. However I keep getting the same error no matter which spike sorting image I use from docker. Could I get some help? I am just following the tutorial. 

Here is my input: 
sorter_params = ss.get_default_sorter_params('combinato')
# recording is a RecordingExtractor object
sorting_CO = ss.run_sorter(sorter_name="combinato", recording=recording_preprocessed,output_folder="combinato_output",
                            docker_image="spikeinterface/combinato-base:latest",verbose=True, 
                            **sorter_params)

and my Error Message: 
Starting container
Installing spikeinterface==0.99.1 in spikeinterface/combinato-base:latest
Installing extra requirements: ['neo', 'mearec']
Running combinato sorter inside spikeinterface/combinato-base:latest
Stopping container

~/anaconda3/envs/spikeTest/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py:608)     if with_output:
...
    extractor = extractor_class(**new_kwargs)
  File "/root/.local/lib/python3.8/site-packages/spikeinterface/core/binaryfolder.py", line 35, in __init__
    with open(folder_path [/](https://file+.vscode-resource.vscode-cdn.net/) "binary.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/sr/wsdm_1zx6wj1mgw6gg3m43g80000gn/T/spikeinterface_cache/tmpqdx5w1ct/1RCXQKQP/binary.json'

Any help would be much appreciated. I cannot figure out what the binary.json file is and why the image does not have this file or create it when I run the containerized sorter.

**Comment by samuelgarcia** [comment]
I think you have saved your recording in the cache instead of giving an explicit folder.
In short you should replace `rec.save(name='rec_name')` by `rec.save(folder='/path/to/a/folder')`
