### ISSUE TITLE
matlab_for_kilosort image

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spikeinterface-dockerfiles#7]
I think I should move this matlab for kilosort instructions and docker recipe to this repo. Would you all agree?
https://github.com/flatironinstitute/spikeforest/tree/main/devel/matlab_docker

Note that the matlab_for_kilosort cannot be built directly from Dockerfile build -- unfortunately it requires some manual steps, as well as a valid license, to build the image.

@samuelgarcia @bendichter @jsoules @alejoe91

**Comment by samuelgarcia** [comment]
Yes good idea.
